/* Generated By:JJTree: Do not edit this line. ASTQueryTableExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTQueryTableExpression extends SimpleNode {
  public ASTQueryTableExpression(int id) {
    super(id);
  }

  public ASTQueryTableExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb5f946056e13d641ccfd2de5e998a85 (do not edit this line) */
