/* Generated By:JJTree: Do not edit this line. ASTSQLUnaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLUnaryExpression extends SimpleNode {
  public ASTSQLUnaryExpression(int id) {
    super(id);
  }

  public ASTSQLUnaryExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=eb425e3b9339336a0aea4c4e6c75b742 (do not edit this line) */
