/* Generated By:JJTree: Do not edit this line. ASTSQLMultiplicativeExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLMultiplicativeExpression extends SimpleNode {
  public ASTSQLMultiplicativeExpression(int id) {
    super(id);
  }

  public ASTSQLMultiplicativeExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2e93a0d57674ea4ca6b507ff83019c5c (do not edit this line) */
