/* Generated By:JJTree: Do not edit this line. ASTSQLSimpleExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLSimpleExpression extends SimpleNode {
  public ASTSQLSimpleExpression(int id) {
    super(id);
  }

  public ASTSQLSimpleExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9796ecdebcf44b54c2669c34f07649a7 (do not edit this line) */
