/* Generated By:JJTree: Do not edit this line. ASTSelectList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSelectList extends SimpleNode {
  public ASTSelectList(int id) {
    super(id);
  }

  public ASTSelectList(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=476ab14b25a4c656a36124c7df3181dc (do not edit this line) */
