/* Generated By:JJTree: Do not edit this line. ASTSQLInClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLInClause extends SimpleNode {
  public ASTSQLInClause(int id) {
    super(id);
  }

  public ASTSQLInClause(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a4dee3e46a8ef169a28ddc93bb77198e (do not edit this line) */
