/* Generated By:JJTree: Do not edit this line. ASTSQLLikeClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLLikeClause extends SimpleNode {
  public ASTSQLLikeClause(int id) {
    super(id);
  }

  public ASTSQLLikeClause(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8d1887b48e4dab3a12da1a8870113068 (do not edit this line) */
