/* Generated By:JJTree: Do not edit this line. ASTSQLPrimaryExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLPrimaryExpression extends SimpleNode {
  public ASTSQLPrimaryExpression(int id) {
    super(id);
  }

  public ASTSQLPrimaryExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2aba0e3da40169c8db44c57c8897a9c8 (do not edit this line) */
