/* Generated By:JJTree: Do not edit this line. ASTSQLRelationalOperatorExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLRelationalOperatorExpression extends SimpleNode {
  public ASTSQLRelationalOperatorExpression(int id) {
    super(id);
  }

  public ASTSQLRelationalOperatorExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d25fcc7e7661f0d118710fc660bb6e7e (do not edit this line) */
