/* Generated By:JavaCC: Do not edit this line. SqlParserTreeConstants.java Version 5.0 */
package mx.itesm.ddb.parser;



public interface SqlParserTreeConstants
{
  public int JJTCOMPILATIONUNIT = 0;
  public int JJTQUERY = 1;
  public int JJTSELECTLIST = 2;
  public int JJTSELECTITEM = 3;
  public int JJTSQLSIMPLEEXPRESSION = 4;
  public int JJTSQLMULTIPLICATIVEEXPRESSION = 5;
  public int JJTSQLEXPONENTEXPRESSION = 6;
  public int JJTSQLUNARYEXPRESSION = 7;
  public int JJTSQLPRIMARYEXPRESSION = 8;
  public int JJTSQLEXPRESSION = 9;
  public int JJTSQLANDEXPRESSION = 10;
  public int JJTSQLUNARYLOGICALEXPRESSION = 11;
  public int JJTEXISTSCLAUSE = 12;
  public int JJTSQLRELATIONALEXPRESSION = 13;
  public int JJTSQLEXPRESSIONLIST = 14;
  public int JJTSQLRELATIONALOPERATOREXPRESSION = 15;
  public int JJTSQLINCLAUSE = 16;
  public int JJTSQLBETWEENCLAUSE = 17;
  public int JJTSQLLIKECLAUSE = 18;
  public int JJTISNULLCLAUSE = 19;
  public int JJTFROMCLAUSE = 20;
  public int JJTQUERYTABLEEXPRESSION = 21;
  public int JJTWHERECLAUSE = 22;


  public String[] jjtNodeName = {
    "CompilationUnit",
    "Query",
    "SelectList",
    "SelectItem",
    "SQLSimpleExpression",
    "SQLMultiplicativeExpression",
    "SQLExponentExpression",
    "SQLUnaryExpression",
    "SQLPrimaryExpression",
    "SQLExpression",
    "SQLAndExpression",
    "SQLUnaryLogicalExpression",
    "ExistsClause",
    "SQLRelationalExpression",
    "SQLExpressionList",
    "SQLRelationalOperatorExpression",
    "SQLInClause",
    "SQLBetweenClause",
    "SQLLikeClause",
    "IsNullClause",
    "FromClause",
    "QueryTableExpression",
    "WhereClause",
  };
}
/* JavaCC - OriginalChecksum=a0d38294dff0e38e78782750ca3c6c73 (do not edit this line) */
