/* Generated By:JavaCC: Do not edit this line. SqlParserTreeConstants.java Version 5.0 */
package mx.itesm.ddb.parser;

public interface SqlParserTreeConstants
{
  public int JJTQUERYSTATEMENT = 0;
  public int JJTQUERY = 1;
  public int JJTSELECTLIST = 2;
  public int JJTSELECTITEM = 3;
  public int JJTSQLSIMPLEEXPRESSION = 4;
  public int JJTSQLMULTIPLICATIVEEXPRESSION = 5;
  public int JJTSQLUNARYEXPRESSION = 6;
  public int JJTSQLPRIMARYEXPRESSION = 7;
  public int JJTSQLEXPRESSION = 8;
  public int JJTSQLANDEXPRESSION = 9;
  public int JJTSQLUNARYLOGICALEXPRESSION = 10;
  public int JJTEXISTSCLAUSE = 11;
  public int JJTSQLRELATIONALEXPRESSION = 12;
  public int JJTSQLEXPRESSIONLIST = 13;
  public int JJTSQLRELATIONALOPERATOREXPRESSION = 14;
  public int JJTSQLINCLAUSE = 15;
  public int JJTSQLBETWEENCLAUSE = 16;
  public int JJTSQLLIKECLAUSE = 17;
  public int JJTISNULLCLAUSE = 18;
  public int JJTFROMCLAUSE = 19;
  public int JJTQUERYTABLEEXPRESSION = 20;
  public int JJTWHERECLAUSE = 21;


  public String[] jjtNodeName = {
    "QueryStatement",
    "Query",
    "SelectList",
    "SelectItem",
    "SQLSimpleExpression",
    "SQLMultiplicativeExpression",
    "SQLUnaryExpression",
    "SQLPrimaryExpression",
    "SQLExpression",
    "SQLAndExpression",
    "SQLUnaryLogicalExpression",
    "ExistsClause",
    "SQLRelationalExpression",
    "SQLExpressionList",
    "SQLRelationalOperatorExpression",
    "SQLInClause",
    "SQLBetweenClause",
    "SQLLikeClause",
    "IsNullClause",
    "FromClause",
    "QueryTableExpression",
    "WhereClause",
  };
}
/* JavaCC - OriginalChecksum=922a410bc212138748274b7a11417bb7 (do not edit this line) */
