/* Generated By:JJTree: Do not edit this line. ASTFromClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTFromClause extends SimpleNode {
  public ASTFromClause(int id) {
    super(id);
  }

  public ASTFromClause(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3e1af3d29ff44384b41036339bc626e (do not edit this line) */
