/* Generated By:JJTree: Do not edit this line. ASTIsNullClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTIsNullClause extends SimpleNode {
  public ASTIsNullClause(int id) {
    super(id);
  }

  public ASTIsNullClause(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c5e96e3847b670c20f195d018393596e (do not edit this line) */
