/* Generated By:JJTree: Do not edit this line. ASTQueryTableExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTQueryTableExpression extends SimpleNode {
  public ASTQueryTableExpression(int id) {
    super(id);
  }

  public ASTQueryTableExpression(SqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=698c535b39150ede05ffea97e79e56de (do not edit this line) */
