/* Generated By:JJTree: Do not edit this line. ASTSQLBetweenClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLBetweenClause extends SimpleNode {
  public ASTSQLBetweenClause(int id) {
    super(id);
  }

  public ASTSQLBetweenClause(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e2ec953c694a473d952086bd55291a1a (do not edit this line) */
