/* Generated By:JJTree: Do not edit this line. ASTSQLExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLExpression extends SimpleNode {
  public ASTSQLExpression(int id) {
    super(id);
  }

  public ASTSQLExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9a4e9dad23e207ae77c6873fac721cdc (do not edit this line) */
