/* Generated By:JJTree: Do not edit this line. ASTSQLUnaryLogicalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=mx.itesm.ddb.util.SqlNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;



public
class ASTSQLUnaryLogicalExpression extends SimpleNode {
  public ASTSQLUnaryLogicalExpression(int id) {
    super(id);
  }

  public ASTSQLUnaryLogicalExpression(SqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3e515318c7b36e23c97e8402b06f7ba9 (do not edit this line) */
