/* Generated By:JJTree: Do not edit this line. ASTSQLAndExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLAndExpression extends SimpleNode {
  public ASTSQLAndExpression(int id) {
    super(id);
  }

  public ASTSQLAndExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=53a0f23e49a3b0d44082e735dfaa47ee (do not edit this line) */
