/* Generated By:JJTree: Do not edit this line. ASTSQLBetweenClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=mx.itesm.ddb.util.SqlNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLBetweenClause extends SimpleNode {
  public ASTSQLBetweenClause(int id) {
    super(id);
  }

  public ASTSQLBetweenClause(SqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5317f667546b4e3bbd4854d8efa2393a (do not edit this line) */
