/* Generated By:JJTree: Do not edit this line. ASTSQLExpressionList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLExpressionList extends SimpleNode {
  public ASTSQLExpressionList(int id) {
    super(id);
  }

  public ASTSQLExpressionList(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f7a20ee60d5aae0a5236de1639ffeb50 (do not edit this line) */
