/* Generated By:JJTree: Do not edit this line. ASTSQLSimpleExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=mx.itesm.ddb.util.SqlNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;



public
class ASTSQLSimpleExpression extends SimpleNode {
  public ASTSQLSimpleExpression(int id) {
    super(id);
  }

  public ASTSQLSimpleExpression(SqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1bb37c9a0652413d4dbbd18dfa4bd352 (do not edit this line) */
