/* Generated By:JJTree: Do not edit this line. ASTSQLUnaryLogicalExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLUnaryLogicalExpression extends SimpleNode {
  public ASTSQLUnaryLogicalExpression(int id) {
    super(id);
  }

  public ASTSQLUnaryLogicalExpression(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4390725e5c5ac65d9e0662434c74be2f (do not edit this line) */
