/* Generated By:JJTree: Do not edit this line. ASTSQLRelationalOperatorExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=mx.itesm.ddb.util.SqlNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTSQLRelationalOperatorExpression extends SimpleNode {
  public ASTSQLRelationalOperatorExpression(int id) {
    super(id);
  }

  public ASTSQLRelationalOperatorExpression(SqlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(SqlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e742d91374ab76fe263fb81edbc26cbf (do not edit this line) */
