/* Generated By:JJTree: Do not edit this line. ASTWhereClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mx.itesm.ddb.parser;

public
class ASTWhereClause extends SimpleNode {
  public ASTWhereClause(int id) {
    super(id);
  }

  public ASTWhereClause(SqlParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ac90b47491224bdd6089197a41ca55db (do not edit this line) */
