/* Generated By:JavaCC: Do not edit this line. SqlParserVisitor.java Version 5.0 */
package mx.itesm.ddb.parser;



public interface SqlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTQueryStatement node, Object data);
  public Object visit(ASTQuery node, Object data);
  public Object visit(ASTSelectList node, Object data);
  public Object visit(ASTSelectItem node, Object data);
  public Object visit(ASTSQLSimpleExpression node, Object data);
  public Object visit(ASTSQLMultiplicativeExpression node, Object data);
  public Object visit(ASTSQLUnaryExpression node, Object data);
  public Object visit(ASTSQLPrimaryExpression node, Object data);
  public Object visit(ASTSQLExpression node, Object data);
  public Object visit(ASTSQLAndExpression node, Object data);
  public Object visit(ASTSQLUnaryLogicalExpression node, Object data);
  public Object visit(ASTExistsClause node, Object data);
  public Object visit(ASTSQLRelationalExpression node, Object data);
  public Object visit(ASTSQLExpressionList node, Object data);
  public Object visit(ASTSQLRelationalOperatorExpression node, Object data);
  public Object visit(ASTSQLInClause node, Object data);
  public Object visit(ASTSQLBetweenClause node, Object data);
  public Object visit(ASTSQLLikeClause node, Object data);
  public Object visit(ASTIsNullClause node, Object data);
  public Object visit(ASTFromClause node, Object data);
  public Object visit(ASTQueryTableExpression node, Object data);
  public Object visit(ASTWhereClause node, Object data);
}
/* JavaCC - OriginalChecksum=66ba3045e3457019fc340f86e5948d00 (do not edit this line) */
