/* Generated By:JJTree&JavaCC: Do not edit this line. SqlParserConstants.java */
package mx.itesm.ddb.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_ALL = 6;
  /** RegularExpression Id. */
  int K_AND = 7;
  /** RegularExpression Id. */
  int K_ANY = 8;
  /** RegularExpression Id. */
  int K_AS = 9;
  /** RegularExpression Id. */
  int K_ASC = 10;
  /** RegularExpression Id. */
  int K_BETWEEN = 11;
  /** RegularExpression Id. */
  int K_DESC = 12;
  /** RegularExpression Id. */
  int K_DISTINCT = 13;
  /** RegularExpression Id. */
  int K_EXISTS = 14;
  /** RegularExpression Id. */
  int K_FROM = 15;
  /** RegularExpression Id. */
  int K_IN = 16;
  /** RegularExpression Id. */
  int K_IS = 17;
  /** RegularExpression Id. */
  int K_LIKE = 18;
  /** RegularExpression Id. */
  int K_NOT = 19;
  /** RegularExpression Id. */
  int K_NULL = 20;
  /** RegularExpression Id. */
  int K_OR = 21;
  /** RegularExpression Id. */
  int K_SELECT = 22;
  /** RegularExpression Id. */
  int K_WHERE = 23;
  /** RegularExpression Id. */
  int S_NUMBER = 24;
  /** RegularExpression Id. */
  int FLOAT = 25;
  /** RegularExpression Id. */
  int INTEGER = 26;
  /** RegularExpression Id. */
  int DIGIT = 27;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 28;
  /** RegularExpression Id. */
  int LETTER = 29;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 30;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"AS\"",
    "\"ASC\"",
    "\"BETWEEN\"",
    "\"DESC\"",
    "\"DISTINCT\"",
    "\"EXISTS\"",
    "\"FROM\"",
    "\"IN\"",
    "\"IS\"",
    "\"LIKE\"",
    "\"NOT\"",
    "\"NULL\"",
    "\"OR\"",
    "\"SELECT\"",
    "\"WHERE\"",
    "<S_NUMBER>",
    "<FLOAT>",
    "<INTEGER>",
    "<DIGIT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "\";\"",
    "\"*\"",
    "\",\"",
    "\".*\"",
    "\"+\"",
    "\"-\"",
    "\"||\"",
    "\"/\"",
    "\"**\"",
    "\"(\"",
    "\")\"",
  };

}
